# Generated by Django 3.1.7 on 2021-04-04 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 4, 20, 1, 33, 880613)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.UUIDField(default='c99eec7bc8fc4e69af319eec746ab9df', editable=False, primary_key=True, serialize=False),
        ),
    ]
