# Generated by Django 2.2.17 on 2021-04-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account',
            field=models.CharField(choices=[(None, ''), ('Host', 'Host'), ('Tenant', 'Tenant')], help_text='What kind of account is this?', max_length=6),
        ),
    ]
