# Generated by Django 2.2.17 on 2021-04-03 17:16

from django.db import migrations, models
import milk_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='uniName',
            new_name='university',
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture',
            field=models.ImageField(upload_to=milk_app.models.generate_filename_listing),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=milk_app.models.generate_filename_userpic),
        ),
    ]
