# Generated by Django 2.2.17 on 2021-04-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0002_remove_listing_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='id',
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
