# Generated by Django 2.2.17 on 2021-04-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0002_auto_20210402_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='picture',
            field=models.ImageField(blank=True, upload_to='listing_images'),
        ),
    ]
