# Generated by Django 3.1.7 on 2021-04-04 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0002_auto_20210404_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 4, 20, 3, 38, 279130)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
