# Generated by Django 3.1.7 on 2021-04-04 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0003_auto_20210404_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
